title: Pluto Skyrim VR
description: >-
  A guide for realistic, balanced and stable Skyrim VR modding for experienced users. Tested on Meta Quest 3, AMD Ryzen 5 5600X, NVIDIA Geforce RTX 4080. Since 2019.
url: "https://pluto-skyrimvr.github.io"

markdown: GFM

remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-readme-index
  - jekyll-remote-theme

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

exclude:
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - work_notes
